package models;

import java.util.List;

public class Doctor {
    public String name;
    public String doctorId;
    public SpecType speciality;
    public List<Slot> slots;

    Doctor(String name, SpecType speciality) {
        this.name = name;
        this.speciality = speciality;
        this.doctorId = "autogenerated";
    }

    public String getName() {
        return name;
    }

    public Doctor getDoctor(String doctorId) {
        return this;
    }

    public SpecType getSpeciality() {
        return speciality;
    }

    public void setSlot() {

    }

    public void setSlots() {

    }

    public void getSlot() {

    }

    public void cancelSlot() {

    }
}
